name: 'Issue & Pull Request Auto Labeling and Assigning'
description: 'Apply labels and/or set assignees based on issue/PR contents'
inputs:
  github-token:
    description: 'Github token'
    required: true
  parameters:
    description: "JSON array of keywords to look for and labels and assignees to be set when there's a keyword match"
    required: true
  title-or-body:
    description: 'Whether to check the issue title, the issue body, or both for matching keywords'
    required: false
    default: 'both'

outputs:
  title:
    description: 'Title of Issue'
  body:
    description: 'Body of Issue'
  labeled:
    description: '"true" if labeled otherwise "false"'
  assigned:
    description: '"true" if assigned otherwise "false"'
runs:
  using: 'node16'
  main: 'lib/index.js'
branding:
  icon: alert-circle
  color: gray-dark
